#!/usr/bin/env bash
# Serve the contract's cluster upstream DNS on the egress host's internal address.
#
# 워커에 직접 egress 가 없는 사이트에서는 CoreDNS 가 노드 resolv.conf 를 물어도
# 그 resolver 에 닿지 못해 외부 이름이 전부 SERVFAIL 이 된다. Squid 가 HTTP egress 를
# 한 곳으로 모으는 것과 같은 방식으로, DNS 도 egress 호스트의 내부 IP 하나로 모은다.
# systemd-resolved 는 이미 노드에서 도는 stub resolver 이므로 추가 listener 만 연다.
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
CHECK_ONLY=false
DROPIN=/etc/systemd/resolved.conf.d/10-sadp-cluster-upstream.conf

usage() {
  echo "usage: sudo $0 [--check]" >&2
}

while (($#)); do
  case "$1" in
    --check) CHECK_ONLY=true ;;
    -h|--help) usage; exit 0 ;;
    *) usage; exit 2 ;;
  esac
  shift
done

[[ ${EUID} -eq 0 ]] || { echo "[FAIL] root 권한이 필요함" >&2; exit 1; }
command -v python3 >/dev/null || { echo "[FAIL] python3가 필요함" >&2; exit 1; }

cd "${ROOT}"
python3 scripts/site/render-network.py --check

eval "$(python3 - <<'PY'
import yaml
spec = yaml.safe_load(open("contracts/platform-production.yaml", encoding="utf-8"))["spec"]
upstream = str(spec["network"].get("clusterUpstreamDNS") or "").strip()
address, _, port = upstream.rpartition(":")
print(f"UPSTREAM_ADDRESS='{address}'")
print(f"UPSTREAM_PORT='{port}'")
PY
)"

[[ -n ${UPSTREAM_ADDRESS} ]] || {
  echo "[FAIL] network.clusterUpstreamDNS 가 비어 있음. site.env 의 CLUSTER_UPSTREAM_DNS 를 먼저 정하라" >&2
  exit 1
}
[[ ${UPSTREAM_PORT} == 53 ]] || {
  echo "[FAIL] systemd-resolved stub listener 는 53 번만 연다(계약값 ${UPSTREAM_PORT})" >&2
  exit 1
}

# pipefail 이 켜져 있으므로 `cmd | grep -q` 는 쓰지 않는다(install-squid-egress.sh 와 같은 이유).
listener_has() { grep -Fq "$1" <<<"$2"; }

host_addrs=$(ip -4 addr show)
listener_has " ${UPSTREAM_ADDRESS}/" "${host_addrs}" || {
  echo "[FAIL] 이 호스트에 upstream DNS 주소 ${UPSTREAM_ADDRESS}가 없음. egress 호스트에서 실행하라" >&2
  exit 1
}

if [[ ${CHECK_ONLY} == true ]]; then
  systemctl is-active --quiet systemd-resolved || {
    echo "[FAIL] systemd-resolved 비활성" >&2
    exit 1
  }
  listeners=$(ss -lun)
  listener_has "${UPSTREAM_ADDRESS}:53" "${listeners}" || {
    echo "[FAIL] ${UPSTREAM_ADDRESS}:53 listener 없음" >&2
    exit 1
  }
  echo "[OK] cluster upstream DNS listener 확인"
  exit 0
fi

systemctl is-active --quiet systemd-resolved || {
  echo "[FAIL] systemd-resolved 가 꺼져 있음. 이 스크립트는 다른 resolver 를 설치하지 않는다" >&2
  exit 1
}

install -d -m 0755 /etc/systemd/resolved.conf.d
cat >"${DROPIN}" <<EOF
# Generated by scripts/node/install-dns-forwarder.sh. Do not edit.
# CoreDNS(워커 포함)가 forward 대상으로 쓰는 내부 주소. 기존 127.0.0.53 stub 은 그대로 둔다.
[Resolve]
DNSStubListenerExtra=${UPSTREAM_ADDRESS}
EOF

systemctl restart systemd-resolved

listener_ready=false
for _ in {1..20}; do
  listeners=$(ss -lun)
  if listener_has "${UPSTREAM_ADDRESS}:53" "${listeners}"; then
    listener_ready=true
    break
  fi
  sleep 0.25
done
[[ ${listener_ready} == true ]] || {
  echo "[FAIL] systemd-resolved 가 ${UPSTREAM_ADDRESS}:53 에 bind 하지 않음" >&2
  exit 1
}

echo "[OK] ${UPSTREAM_ADDRESS}:53 에서 cluster upstream DNS 제공"
echo "[NEXT] CoreDNS 가 새 forward 대상을 읽도록 control-plane 에서 실행하라:"
echo "  kubectl -n kube-system rollout restart deploy/rke2-coredns-rke2-coredns"
