#!/usr/bin/env bash
# 노드 inotify 한도를 SADP 하한 이상으로 고정한다(각 노드에서 root).
#
# Ubuntu 기본 fs.inotify.max_user_instances=128은 한 노드에 Pod가 몰리면(다른 worker cordon 등)
# 바로 바닥난다. 실제 사이트 재설치에서 NATS reloader sidecar가 "too many open files"로 죽고,
# NATS Service endpoint가 비어 Devtron 구성요소가 줄줄이 CrashLoop에 빠졌다.
#
#   sudo bash ./sadp --install-node-sysctl            # 계획(현재값·목표값, 변경 없음)
#   sudo bash ./sadp --install-node-sysctl --apply    # /etc/sysctl.d에 기록하고 sysctl -p
#   bash ./sadp --install-node-sysctl --check         # 하한 미만이면 [FAIL]/[NEXT]
#
# 커널 값만 바꾸며 서비스나 노드를 재시작하지 않는다. 이미 더 큰 값이면 낮추지 않는다.
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
MODE=plan
# 회귀 시험이 실제 커널과 /etc를 건드리지 않도록 경로만 바꿀 수 있게 둔다.
PROC_SYS=${SADP_PROC_SYS:-/proc/sys}
SYSCTL_FILE=${SADP_SYSCTL_FILE:-/etc/sysctl.d/90-sadp-inotify.conf}

while (($#)); do
  case "$1" in
    --apply) MODE=apply ;;
    --check) MODE=check ;;
    -h|--help) echo "usage: sudo bash ./sadp --install-node-sysctl [--apply | --check]"; exit 0 ;;
    *) echo "usage: sudo bash ./sadp --install-node-sysctl [--apply | --check]" >&2; exit 2 ;;
  esac
  shift
done

# 하한은 scripts/lib/diagnose.py 한 곳에 둔다. doctor/preflight가 같은 값으로 판정한다.
mapfile -t limits < <(python3 "${ROOT}/scripts/lib/diagnose.py" node-limits)

current_value() {
  local key=$1 path
  path=${PROC_SYS}/${key//.//}
  [[ -r ${path} ]] || { echo ""; return 0; }
  tr -d '[:space:]' <"${path}"
}

low=false
content="# Generated by scripts/node/install-node-sysctl.sh. Do not edit.
# Pod가 한 노드에 몰려도 inotify가 바닥나지 않게 하는 SADP 하한. 기존 값이 더 크면 유지한다."
for entry in "${limits[@]}"; do
  key=${entry%%=*}
  minimum=${entry#*=}
  current=$(current_value "${key}")
  target=${minimum}
  if [[ ${current} =~ ^[0-9]+$ ]] && ((current > minimum)); then
    target=${current}
  fi
  if [[ ! ${current} =~ ^[0-9]+$ ]] || ((current < minimum)); then
    low=true
    status="부족"
  else
    status="충족"
  fi
  printf '[INFO] %s 현재=%s 하한=%s 목표=%s (%s)\n' "${key}" "${current:-읽기 실패}" "${minimum}" "${target}" "${status}"
  content+=$'\n'"${key} = ${target}"
done

if [[ ${MODE} == check ]]; then
  if [[ ${low} == true ]]; then
    echo "[FAIL] 이 노드의 inotify 한도가 SADP 하한 미만" >&2
    echo "[NEXT] sudo bash ./sadp --install-node-sysctl (계획) → --apply (재시작 불필요)" >&2
    exit 1
  fi
  echo "[OK]   inotify 한도가 SADP 하한 이상"
  exit 0
fi

if [[ ${MODE} == plan ]]; then
  echo "[PLAN] ${SYSCTL_FILE}에 다음을 기록하고 sysctl -p로 즉시 반영(재시작 없음):"
  printf '%s\n' "${content}" | sed 's/^/       /'
  [[ ${low} == true ]] || echo "[INFO] 현재 값이 이미 하한 이상이다. --apply는 같은 값을 파일로 고정만 한다"
  echo "[INFO] 계획만 출력함. 적용하려면 --apply"
  exit 0
fi

[[ ${EUID} -eq 0 ]] || { echo "[FAIL] root 권한이 필요함" >&2; exit 1; }
install -d -m 0755 "$(dirname "${SYSCTL_FILE}")"
printf '%s\n' "${content}" >"${SYSCTL_FILE}.tmp"
chmod 0644 "${SYSCTL_FILE}.tmp"
mv "${SYSCTL_FILE}.tmp" "${SYSCTL_FILE}"
sysctl -p "${SYSCTL_FILE}" >/dev/null
bash "$0" --check
