#!/usr/bin/env bash
# 외부 IdP SNI relay(HAProxy TCP)를 Squid egress 호스트에 설치한다.
#
# Envoy Gateway controller(OIDC discovery)와 data plane(token 교환·JWKS)은 HTTPS_PROXY를 쓰지
# 않는다. worker에 외부 route가 없으면 secure-demo SecurityPolicy가 no route to host로
# Accepted=False가 된다. 외부 route가 있는 egress 호스트 내부 IP의 443에서 SNI만 보고 계약 IdP
# 호스트로 TCP를 넘긴다. TLS를 풀지 않으므로 인증서 검증과 client Secret은 끝단 그대로다.
# Pod는 CoreDNS hosts(platform/dns/rke2-coredns-config.yaml)로 IdP 호스트를 이 주소로 해석한다.
#
#   sudo bash ./sadp --install-idp-relay            # 계획만(기본)
#   sudo bash ./sadp --install-idp-relay --apply    # 설치·재적용
#   sudo bash ./sadp --install-idp-relay --check    # 설치 설정·listener·실제 IdP 경로 확인
#
# 다른 서비스는 재시작하지 않는다. CoreDNS/Envoy Gateway 반영은 control-plane 단계가 맡는다.
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
MODE=plan
SKIP_PACKAGE_INSTALL=false
RENDERED=platform/network/idp-relay/haproxy.cfg
TARGET=/etc/haproxy/haproxy.cfg
HEADER='# Generated by scripts/site/render-network.py. Do not edit.'

usage() {
  echo "usage: sudo bash ./sadp --install-idp-relay [--apply | --check] [--skip-package-install]" >&2
}

while (($#)); do
  case "$1" in
    --apply) MODE=apply ;;
    --check) MODE=check ;;
    --skip-package-install) SKIP_PACKAGE_INSTALL=true ;;
    -h|--help) usage; exit 0 ;;
    *) usage; exit 2 ;;
  esac
  shift
done

command -v python3 >/dev/null || { echo "[FAIL] python3가 필요함" >&2; exit 1; }
cd "${ROOT}"
python3 scripts/site/render-network.py --check >/dev/null || {
  echo "[FAIL] 네트워크 생성물이 계약과 다름. render 후 다시 실행하라" >&2
  exit 1
}

relay_values=$(python3 - <<'PY'
import shlex
import yaml
from urllib.parse import urlsplit

spec = yaml.safe_load(open("contracts/platform-production.yaml", encoding="utf-8"))["spec"]
relay = spec["network"].get("identityProviderRelay") or {}
hosts = spec["network"]["squid"].get("identityProviderDomains") or []
issuer = str((spec.get("identityProvider") or {}).get("issuer") or "")
print("RELAY_ENABLED=" + shlex.quote(str(bool(relay.get("enabled"))).lower()))
# 이전 계약({enabled: true}만 있음)은 render-network.py와 같은 기본값을 쓴다.
print("RELAY_ADDRESS=" + shlex.quote(str(relay.get("address") or spec["network"]["squid"]["internalIP"])))
print("RELAY_PORT=" + shlex.quote(str(relay.get("port") or 443)))
print("RELAY_HOSTS=" + shlex.quote(" ".join(hosts)))
# issuer는 정규화하지 않는다. discovery URL만 끝 '/'를 떼고 만든다.
print("ISSUER_HOST=" + shlex.quote(urlsplit(issuer).hostname or ""))
base = issuer[:-1] if issuer.endswith("/") else issuer
print("DISCOVERY_URL=" + shlex.quote(base + "/.well-known/openid-configuration"))
PY
)
eval "${relay_values}"

if [[ ${RELAY_ENABLED} != true ]]; then
  echo "[FAIL] 계약에서 IdP relay가 꺼져 있음(site.env IDP_RELAY_ENABLED=true 후 render)" >&2
  exit 1
fi
[[ -s ${RENDERED} ]] || { echo "[FAIL] ${RENDERED} 없음. render 후 다시 실행하라" >&2; exit 1; }

# pipefail에서 `cmd | grep -q`는 SIGPIPE로 거짓 실패가 난다(install-squid-egress.sh와 같은 이유).
listener_has() { grep -Fq "$1" <<<"$2"; }

# 실제 TLS 경로 확인: relay 주소로 IdP discovery를 받고, 계약 밖 SNI는 끊기는지 본다.
# 응답 본문과 curl 오류 원문은 출력하지 않는다.
check_relay_path() {
  local status
  status=$(curl -q --silent --output /dev/null --write-out '%{http_code}' \
    --noproxy '*' --proto '=https' --connect-timeout 5 --max-time 20 \
    --resolve "${ISSUER_HOST}:${RELAY_PORT}:${RELAY_ADDRESS}" "${DISCOVERY_URL}" 2>/dev/null) || status=000
  [[ ${status} == 200 ]] || {
    echo "[FAIL] relay 경유 IdP discovery 실패(status=${status}). 이 호스트의 IdP 외부 route·DNS와 haproxy 로그를 확인하라" >&2
    return 1
  }
  if curl -q --silent --output /dev/null --noproxy '*' --connect-timeout 5 --max-time 10 \
      --resolve "example.com:${RELAY_PORT}:${RELAY_ADDRESS}" https://example.com/ 2>/dev/null; then
    echo "[FAIL] 계약 밖 SNI(example.com)가 relay를 통과함" >&2
    return 1
  fi
  echo "[OK] relay 경유 IdP discovery 200, 계약 밖 SNI 차단"
}

check_installed() {
  command -v haproxy >/dev/null || { echo "[FAIL] haproxy 미설치" >&2; return 1; }
  cmp -s "${RENDERED}" "${TARGET}" || {
    echo "[FAIL] 설치된 ${TARGET}가 계약 생성물과 다름. --apply로 다시 적용하라" >&2
    return 1
  }
  haproxy -c -q -f "${TARGET}" || { echo "[FAIL] haproxy 설정 검증 실패" >&2; return 1; }
  systemctl is-active --quiet haproxy || { echo "[FAIL] haproxy service가 active가 아님" >&2; return 1; }
  local listeners
  listeners=$(ss -ltn)
  listener_has "${RELAY_ADDRESS}:${RELAY_PORT}" "${listeners}" || {
    echo "[FAIL] ${RELAY_ADDRESS}:${RELAY_PORT} listener 없음" >&2
    return 1
  }
  check_relay_path
}

if [[ ${MODE} == plan ]]; then
  echo "[PLAN] 외부 IdP SNI relay: ${RELAY_ADDRESS}:${RELAY_PORT} (TLS 종단 없음, 내부 IP에만 bind)"
  echo "[PLAN] relay 대상 IdP 호스트: ${RELAY_HOSTS}"
  echo "[PLAN] haproxy 패키지 설치(없을 때) → ${RENDERED} → ${TARGET} 설치 → 설정 검증 → reload/enable"
  echo "[PLAN] 확인: listener, relay 경유 discovery 200, 계약 밖 SNI 차단"
  if [[ -r ${TARGET} ]]; then
    echo "[PLAN] 설치된 ${TARGET}와 생성물 차이:"
    diff -u "${TARGET}" "${RENDERED}" || true
  fi
  echo "[INFO] 계획만 출력함. 적용하려면 relay 주소를 가진 Squid egress 호스트에서 --apply"
  exit 0
fi

[[ ${EUID} -eq 0 ]] || { echo "[FAIL] root 권한이 필요함" >&2; exit 1; }
host_addrs=$(ip -4 addr show)
listener_has " ${RELAY_ADDRESS}/" "${host_addrs}" || {
  echo "[FAIL] 이 호스트에 relay 주소 ${RELAY_ADDRESS}가 없음. Squid egress 호스트에서 실행하라" >&2
  exit 1
}
command -v curl >/dev/null || { echo "[FAIL] curl이 필요함" >&2; exit 1; }

if [[ ${MODE} == check ]]; then
  check_installed
  echo "[OK] IdP relay 설치 설정, service, listener 확인"
  exit 0
fi

# 다른 용도의 HAProxy 설정을 덮어쓰면 그 서비스가 조용히 사라진다. SADP 생성물만 교체한다.
if [[ -f ${TARGET} && $(head -n1 "${TARGET}") != "${HEADER}" ]]; then
  echo "[FAIL] ${TARGET}가 SADP 생성물이 아님. 기존 HAProxy 용도를 확인한 뒤 수동으로 정리하라" >&2
  exit 1
fi

if ! command -v haproxy >/dev/null; then
  [[ ${SKIP_PACKAGE_INSTALL} == false ]] || {
    echo "[FAIL] --skip-package-install을 썼지만 haproxy가 설치되어 있지 않음" >&2
    exit 1
  }
  # relay는 Squid 다음에 설치된다. package mirror는 Squid allowlist에 있으므로 계약 proxy로 받는다.
  source platform/network/proxy.env
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y haproxy
fi

haproxy -c -q -f "${RENDERED}" || { echo "[FAIL] 생성된 haproxy 설정 검증 실패" >&2; exit 1; }
was_active=false
systemctl is-active --quiet haproxy 2>/dev/null && was_active=true
backup_dir=/var/backups/sadp-idp-relay
install -d -m 0700 "${backup_dir}"
[[ ! -f ${TARGET} ]] || cp -a "${TARGET}" "${backup_dir}/haproxy.cfg.$(date -u +%Y%m%dT%H%M%SZ)"
install -D -m 0644 "${RENDERED}" "${TARGET}"
if [[ ${was_active} == true ]]; then
  systemctl reload haproxy
else
  systemctl enable --now haproxy
fi

listener_ready=false
for _ in {1..20}; do
  listeners=$(ss -ltn)
  if listener_has "${RELAY_ADDRESS}:${RELAY_PORT}" "${listeners}"; then
    listener_ready=true
    break
  fi
  sleep 0.25
done
[[ ${listener_ready} == true ]] || {
  echo "[FAIL] haproxy가 ${RELAY_ADDRESS}:${RELAY_PORT}에 bind하지 않음" >&2
  exit 1
}
check_installed
echo "[OK] IdP relay 설치 완료"
echo "[NEXT] control-plane에서 CoreDNS hosts를 반영하고 Envoy Gateway가 새 해석을 쓰게 하라:"
echo "  kubectl apply -f platform/dns/rke2-coredns-config.yaml"
echo "  kubectl -n kube-system rollout status deploy/rke2-coredns-rke2-coredns"
echo "  kubectl -n envoy-gateway-system rollout restart deploy/envoy-gateway"
