apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: devtroncd
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: platform-system
  sources:
  - chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 2.9.0
    helm:
      releaseName: external-secrets
      valueFiles:
      - $values/platform/external-secrets/values-beta.yaml
  - repoURL: https://forgejo.example.invalid/example/sadp.git
    targetRevision: main
    ref: values
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions:
    - .status.terminatingReplicas
  - group: apps
    kind: ReplicaSet
    jqPathExpressions:
    - .status.terminatingReplicas
