apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: devtroncd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana-community.github.io/helm-charts
    targetRevision: 18.9.1
    helm:
      valuesObject:
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          useTestSchema: true
          image:
            pullPolicy: IfNotPresent
          limits_config:
            retention_period: 168h
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 20Gi
            storageClass: local-path
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: '2'
              memory: 2Gi
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        gateway:
          enabled: false
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        lokiCanary:
          enabled: false
        test:
          enabled: false
        sidecar:
          image:
            pullPolicy: IfNotPresent
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions:
    - .status.terminatingReplicas
  - group: apps
    kind: ReplicaSet
    jqPathExpressions:
    - .status.terminatingReplicas
  - group: apps
    kind: StatefulSet
    jqPathExpressions:
    - .spec.volumeClaimTemplates[].status
